apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-influxdb
  labels:
    app: {{ .Release.Name }}-influxdb

spec:
  serviceName: {{ .Release.Name }}-influxdb
  replicas: 1

  selector:
    matchLabels:
      app: {{ .Release.Name }}-influxdb

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-influxdb

    spec:
      containers:
        - name: influxdb
          image: {{ .Values.InfluxDB.image | default "influxdb:2.7.11" }}

          ports:
            - name: http
              containerPort: 8086
              protocol: TCP

          resources:
            requests:
              memory: "4Gi"
              cpu: "1250m"
            limits:
              memory: "4Gi"
              cpu: "1500m"

          volumeMounts:
            - name: influxdb-storage
              mountPath: /var/lib/influxdb2

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-influxdb-config

      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-influxdb-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-influxdb-pvc
  labels:
    app: {{ .Release.Name }}-influxdb

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: {{ default "gp3" .Values.InfluxDB.persistence.storageClassName }}

  resources:
    requests:
      storage: {{ .Values.InfluxDB.persistence.size | default "30Gi" }}