apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-influxdb
  labels:
    app: {{ .Release.Name }}-influxdb

spec:
  type: {{ .Values.InfluxDB.service.type | default "ClusterIP" }}

  ports:
    - name: http
      port: 8086
      targetPort: 8086
      protocol: TCP

  selector:
    app: {{ .Release.Name }}-influxdb