apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-config
data:
  POSTGRES_DB: {{ .Values.db.database | quote }}
  POSTGRES_USER: {{ .Values.db.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}