apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-pt-service-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-pt-service-role
  namespace: {{ .Release.Namespace }}

rules:

  # ==========================================
  # Pods
  # ==========================================
  # Create, read, monitor and delete K6/JMeter
  # worker pods.
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - watch
      - delete

  # ==========================================
  # Pod Logs
  # ==========================================
  # Read worker pod logs.
  - apiGroups: [""]
    resources:
      - pods/log
    verbs:
      - get

  # ==========================================
  # Services
  # ==========================================
  # Required only if the application creates
  # and manages Services for worker pods.
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete

  # ==========================================
  # Events
  # ==========================================
  # Useful for checking scheduling/startup
  # failures of worker pods.
  - apiGroups: [""]
    resources:
      - events
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-pt-service-rolebinding
  namespace: {{ .Release.Namespace }}

subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-pt-service-sa
    namespace: {{ .Release.Namespace }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-pt-service-role
